import { ColorVariableData, TypographyVariableData, ComponentConfig } from '../../shared/types';

function rgbToHex(r: number, g: number, b: number): string {
  const toHex = (v: number) => Math.round(v * 255).toString(16).padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

export function generateMarkdown(
  colors?: ColorVariableData,
  typography?: TypographyVariableData,
  components?: ComponentConfig[]
): string {
  const lines: string[] = [];
  lines.push('# Design System');
  lines.push('');
  lines.push('> Generated by Design System Generator Figma Plugin');
  lines.push('');

  if (colors) {
    lines.push('## Colors');
    lines.push('');

    lines.push('### Primitive Colors');
    lines.push('');
    lines.push('| Token | Hex |');
    lines.push('|-------|-----|');
    for (const v of colors.primitive.variables) {
      const hex = rgbToHex(v.value.r, v.value.g, v.value.b);
      lines.push(`| \`${v.name}\` | ![](https://via.placeholder.com/16/${hex.replace('#', '')}?text=+) \`${hex}\` |`);
    }
    lines.push('');

    lines.push('### System Colors');
    lines.push('');
    lines.push('| Token | Hex |');
    lines.push('|-------|-----|');
    for (const v of colors.system.variables) {
      const hex = rgbToHex(v.value.r, v.value.g, v.value.b);
      lines.push(`| \`${v.name}\` | \`${hex}\` |`);
    }
    lines.push('');

    lines.push('### Semantic Colors');
    lines.push('');
    lines.push('| Token | Hex | Description |');
    lines.push('|-------|-----|-------------|');
    for (const v of colors.semantic.variables) {
      const hex = rgbToHex(v.value.r, v.value.g, v.value.b);
      lines.push(`| \`${v.name}\` | \`${hex}\` | ${v.description ?? ''} |`);
    }
    lines.push('');
  }

  if (typography) {
    lines.push('## Typography & Spacing');
    lines.push('');

    const fontVars = typography.variables.filter(v => v.name.startsWith('font/'));
    const spacingVars = typography.variables.filter(v => v.name.startsWith('spacing/'));

    lines.push('### Font Variables');
    lines.push('');
    lines.push('| Token | Value |');
    lines.push('|-------|-------|');
    for (const v of fontVars) {
      lines.push(`| \`${v.name}\` | \`${v.value}\` |`);
    }
    lines.push('');

    lines.push('### Spacing');
    lines.push('');
    lines.push('| Token | Value (px) |');
    lines.push('|-------|------------|');
    for (const v of spacingVars) {
      lines.push(`| \`${v.name}\` | \`${v.value}px\` |`);
    }
    lines.push('');
  }

  if (components && components.length > 0) {
    lines.push('## Components');
    lines.push('');

    const byCategory = components.reduce((acc, c) => {
      if (!acc[c.category]) acc[c.category] = [];
      acc[c.category].push(c);
      return acc;
    }, {} as Record<string, ComponentConfig[]>);

    for (const [category, comps] of Object.entries(byCategory)) {
      lines.push(`### ${category}`);
      lines.push('');
      for (const comp of comps) {
        lines.push(`#### ${comp.name}`);
        lines.push('');
        lines.push(comp.description);
        lines.push('');
        if (comp.props.length > 0) {
          lines.push('**Props**');
          lines.push('');
          lines.push('| Prop | Type | Required | Default |');
          lines.push('|------|------|----------|---------|');
          for (const prop of comp.props) {
            const type = prop.values ? `\`${prop.values.join(' \\| ')}\`` : `\`${prop.type}\``;
            lines.push(`| \`${prop.name}\` | ${type} | ${prop.required ? '✅' : '—'} | ${prop.defaultValue ?? '—'} |`);
          }
          lines.push('');
        }
        if (comp.variants.length > 0) {
          lines.push(`**Variants:** ${comp.variants.map(v => `\`${v}\``).join(', ')}`);
          lines.push('');
        }
      }
    }
  }

  return lines.join('\n');
}

export function generateStorybookTokens(
  colors?: ColorVariableData,
  typography?: TypographyVariableData
): string {
  const tokens: Record<string, unknown> = {};

  if (colors) {
    tokens.color = {};
    const colorTokens = tokens.color as Record<string, unknown>;

    colorTokens.primitive = {};
    for (const v of colors.primitive.variables) {
      const parts = v.name.split('/');
      const colorName = parts[0];
      const shade = parts[1];
      if (!(colorTokens.primitive as Record<string, unknown>)[colorName]) {
        (colorTokens.primitive as Record<string, unknown>)[colorName] = {};
      }
      ((colorTokens.primitive as Record<string, unknown>)[colorName] as Record<string, unknown>)[shade] = {
        value: rgbToHex(v.value.r, v.value.g, v.value.b),
        type: 'color',
      };
    }

    colorTokens.semantic = {};
    for (const v of colors.semantic.variables) {
      const parts = v.name.split('/');
      let current = colorTokens.semantic as Record<string, unknown>;
      for (let i = 0; i < parts.length - 1; i++) {
        if (!current[parts[i]]) current[parts[i]] = {};
        current = current[parts[i]] as Record<string, unknown>;
      }
      current[parts[parts.length - 1]] = {
        value: rgbToHex(v.value.r, v.value.g, v.value.b),
        type: 'color',
        description: v.description,
      };
    }
  }

  if (typography) {
    tokens.typography = {};
    for (const v of typography.variables) {
      const parts = v.name.split('/');
      let current = tokens.typography as Record<string, unknown>;
      for (let i = 0; i < parts.length - 1; i++) {
        if (!current[parts[i]]) current[parts[i]] = {};
        current = current[parts[i]] as Record<string, unknown>;
      }
      current[parts[parts.length - 1]] = {
        value: v.value,
        type: v.type === 'FLOAT' ? 'number' : 'string',
      };
    }
  }

  return JSON.stringify(tokens, null, 2);
}

export function generateStorybookStory(component: ComponentConfig): string {
  const propsStr = component.props
    .map(p => {
      if (p.type === 'enum' && p.values) {
        return `  ${p.name}: { control: 'select', options: [${p.values.map(v => `'${v}'`).join(', ')}] }`;
      }
      if (p.type === 'boolean') {
        return `  ${p.name}: { control: 'boolean' }`;
      }
      return `  ${p.name}: { control: 'text' }`;
    })
    .join(',\n');

  const defaultArgsStr = component.props
    .filter(p => p.defaultValue !== undefined)
    .map(p => `  ${p.name}: ${typeof p.defaultValue === 'string' ? `'${p.defaultValue}'` : p.defaultValue}`)
    .join(',\n');

  const variantStoriesStr = component.variants
    .map(variant => {
      const storyName = variant.charAt(0).toUpperCase() + variant.slice(1);
      return `export const ${storyName}: Story = {\n  args: {\n    variant: '${variant}',\n  },\n};`;
    })
    .join('\n\n');

  return `import type { Meta, StoryObj } from '@storybook/react';
import { ${component.name} } from './${component.name}';

const meta: Meta<typeof ${component.name}> = {
  title: '${component.category}/${component.name}',
  component: ${component.name},
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  argTypes: {
${propsStr}
  },
  args: {
${defaultArgsStr}
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};

${variantStoriesStr}
`;
}
