import { FigmaExport, ColorVariableData, TypographyVariableData, ComponentConfig } from '../../shared/types';

export function buildFigmaExport(
  colors: ColorVariableData | null,
  typography: TypographyVariableData | null,
  components: ComponentConfig[],
  source: 'plugin' | 'webapp' = 'webapp',
): FigmaExport {
  return {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    source,
    colors,
    typography,
    components,
  };
}

export function parseFigmaExport(json: unknown): FigmaExport | null {
  try {
    const data = json as FigmaExport;
    if (data.version !== '1.0') return null;
    if (!Array.isArray(data.components)) return null;
    return data;
  } catch {
    return null;
  }
}

export function mergeImportedComponents(
  current: ComponentConfig[],
  imported: ComponentConfig[],
): ComponentConfig[] {
  const result = [...current];
  for (const imp of imported) {
    const idx = result.findIndex(c => c.id === imp.id);
    if (idx >= 0) {
      result[idx] = { ...result[idx], ...imp };
    } else {
      result.push(imp);
    }
  }
  return result;
}

export function generateDetailedMarkdown(
  colors: ColorVariableData | null,
  typography: TypographyVariableData | null,
  components: ComponentConfig[],
): string {
  const lines: string[] = [];
  lines.push('# Design System');
  lines.push('');
  lines.push(`> Generated by Design System Hub — ${new Date().toLocaleDateString('ja-JP')}`);
  lines.push('');

  // Components by category
  if (components.length > 0) {
    lines.push('## Components');
    lines.push('');

    const byCategory = components.reduce((acc, c) => {
      if (!acc[c.category]) acc[c.category] = [];
      acc[c.category].push(c);
      return acc;
    }, {} as Record<string, ComponentConfig[]>);

    for (const [category, comps] of Object.entries(byCategory)) {
      lines.push(`### ${category}`);
      lines.push('');
      for (const comp of comps) {
        lines.push(`#### ${comp.name}`);
        lines.push('');
        if (comp.definition) {
          lines.push(comp.definition);
          lines.push('');
        }

        if (comp.variants.length > 0) {
          lines.push(`**Variants:** ${comp.variants.map(v => `\`${v}\``).join(', ')}`);
          lines.push('');
        }

        if (comp.usageExamples) {
          lines.push('**Usage Examples**');
          lines.push('');
          for (const line of comp.usageExamples.split('\n').filter(l => l.trim())) {
            lines.push(`- ${line.trim()}`);
          }
          lines.push('');
        }

        if (comp.doExample || comp.dontExample) {
          lines.push('**Do & Don\'t**');
          lines.push('');
          if (comp.doExample) {
            lines.push('✓ Do:');
            for (const line of comp.doExample.split('\n').filter(l => l.trim())) {
              lines.push(`- ${line.trim()}`);
            }
          }
          if (comp.dontExample) {
            lines.push('✕ Don\'t:');
            for (const line of comp.dontExample.split('\n').filter(l => l.trim())) {
              lines.push(`- ${line.trim()}`);
            }
          }
          lines.push('');
        }

        if (comp.accessibility) {
          lines.push('**Accessibility**');
          lines.push('');
          for (const line of comp.accessibility.split('\n').filter(l => l.trim())) {
            lines.push(`- ${line.trim()}`);
          }
          lines.push('');
        }

        if (comp.states) {
          lines.push('**States**');
          lines.push('');
          lines.push('| State | Description |');
          lines.push('|-------|-------------|');
          for (const line of comp.states.split('\n').filter(l => l.trim())) {
            const [key, ...rest] = line.split(':');
            lines.push(`| \`${key.trim()}\` | ${rest.join(':').trim()} |`);
          }
          lines.push('');
        }

        if (comp.relatedComponents) {
          lines.push('**Related Components**');
          lines.push('');
          for (const line of comp.relatedComponents.split('\n').filter(l => l.trim())) {
            lines.push(`- ${line.trim()}`);
          }
          lines.push('');
        }

        // Style table
        if (Object.keys(comp.styleMap).length > 0) {
          lines.push('**Variant Styles**');
          lines.push('');
          lines.push('| Variant | Background | Text | Border | Radius |');
          lines.push('|---------|-----------|------|--------|--------|');
          for (const [variant, style] of Object.entries(comp.styleMap)) {
            lines.push(`| \`${variant}\` | \`${style.backgroundColor}\` | \`${style.textColor}\` | \`${style.borderColor}\` | ${style.borderRadius}px |`);
          }
          lines.push('');
        }

        lines.push('---');
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}
